CLASSPATH=.:$(JARS_HOME)/backpropagation.jar:$(JARS_HOME)/gnu.regexp-1.1.1/lib/gnu.regexp-1.1.1.jar

all: CornerLearning.class CornerTesting.class

CornerLearning.class: CornerLearning.java

CornerTesting.class: CornerTesting.java

include Makefile_general
